#!/usr/bin/env bash

clear

RED='\033[0;31m'
GRN='\033[0;32m'
YLW='\033[0;33m'
BLU='\033[0;34m'
MAG='\033[0;35m'
CYN='\033[0;36m'
NOC='\033[0m'


printf "        ▄▄▄         \n"
printf "     ▄███▓██▌       \n"
printf " ▐███████████▄      "; printf "${RED}os: ${NOC}freebsd\n"
printf "▐▓▓▀ ████████▓      "; printf "${GRN}wm: ${NOC}wmutils\n"
printf "     ▐▒▄▄           "; printf "${YLW}term: ${NOC}st\n"
printf "         █▀         "; printf "${BLU}sh: ${NOC}bash\n"
printf "       ▄██          "; printf "${MAG}font: ${NOC}scientifica\n"
printf "   ▐▒░░░▒░░░░       \n"
printf "░░░░░▒▒▒▒▒▒░░░░"

if test "$1" = "-s"; then
    scrot -d 1 -q 100
fi
